---
functional:
  - Пользователь должен иметь возможность создавать игру
  - Пользователь должен иметь возможность подключаться к созданной игре
  - Пользователь должен иметь возможность отправить ссылку-приглашение на участие в игре
  - Пользователь должен иметь возможность создавать игру
  - Пользователь должен иметь возможность присоединяться в запущенную игру в качестве зрителя
  - Пользователь должен иметь возможность авторизоваться на сайте с помощью: электронной почты, Github, Discord
  - Пользователь должен иметь возможность восстановить данные о своём аккаунте с помощью: электронной почты, Github, Discord
  - Должен быть раздел "Users rating" отображением рейтинга пользователей
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть кроссплатформенным
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен быть способен выдерживать 500 запросов в секунду
implicit:
  - Игра начинается только при налчии 2-ух участников
  - На этапе авторизации пользователь должен иметь возможность выбирать чек-бокс со значением "Сохранить данные для входа" 
  -* После успешной авторизации надпись "Successfully authenticated" не должна появляться более 1 раза
  - В разделе чата "General" рядом с каждым сообщением пользователя должно быть время отправки
  - В разделе чата "Notification" не должно быть диалогового окна с возможностью ввода символов
  - В разделе "Settings" должна быть возможность изменения имени пользователя
  - В разделе "Settings" должна быть возможность выбора языка программирования в качестве вашего оружия для сражения
  - В разделе "Settings" должна быть возможность выбора звукового сопровождения при выигрыше в матче
  - В разделе "Settings" должна быть возможность регулировка громкости звукового сопровождения при выигрыше в матче
  - В разделе 
  -
  - Кнопка "Fight" должна быть красного цвета
  - Кнопка "Create a game" должна быть зелёного цвета
  - Кнопка "Show" должна быть бледно-синего цвета
  - Кнопки "Lobby/Tournaments/History" должны быть выделены серым цветом при нажатии
  - Кнопки "Lobby/Tournaments/History" должны быть выделены тёмно-серым цветом в момент не задействования
  - 
