---
functional:
  - Пользователь должен иметь возможность авторизоваться на сайте с помощью: электронной почты, Github, Discord
  - Пользователь должен иметь возможность восстановить данные о своём аккаунте с помощью: электронной почты, Github, Discord
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть кроссплатформенным
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен быть способен выдерживать 500 запросов в секунду
implicit:
  - На этапе авторизации пользователь должен иметь возможность выбирать чек-бокс со значением "Сохранить данные для входа" 
