---
functional:
  - Пользователь должен иметь возможность зарегистрироваться с помощью электронной почты
  - Пользователь должен получить письмо-подтверждение о регистрации на электронную почту
  - Пользователь должен иметь возможность авторизоваться на сайте с помощью электронной почты, Github, Discord
  - Пользователь должен иметь возможность восстановить пароль с помощью электронной почты
  - Пользователь должен иметь возможность создавать игру с ботом
  - Пользователь должен иметь возможность подключаться к созданной игре в качестве зрителя
  - Пользователь должен иметь возможность отправить приглашение на участие в игре
  - Пользователь должен иметь возможность создавать игру открытую для всех пользователей
  - Пользователь должен иметь возможность присоединяться к созданной игре в качестве участника
  - Пользователь должен иметь возможность при создании игры присвоить игре 4-ре уровня сложности - elemenatry, easy, medium, hard
  - Пользователь должен иметь возможность создавать игру из предложенного списка игр или выбирать игру по тегам
  - Пользователь должен иметь возможность создавать турнир
  - Пользователь должен иметь возможность просматривать свою статистику игр
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть кроссплатформенным - адаптивная вёрстка для ПК и мобильных устройств
  - Сайт должен быть совместим с последними версиями браузеров - Google Chrome, Safari, Firefox, Opera, Яндекс. Браузер, Microsoft Edge
  - Сайт должен быть способен выдерживать 500 запросов в секунду
implicit:
  - Игра начинается только при присутствии 2-ух участников
  - Пользователь должен иметь возможность ограничивать время игры от 3 до 60 минут
  - В разделе "Create a geme" должны быть Теги(collections, hash-maps, maths, strings, rest)  по которым можно отсортировать предложенные игры
  - На этапе авторизации пользователь должен иметь возможность выбирать чек-бокс со значением "Сохранить данные для входа" 
  - В разделе чата "General" рядом с каждым сообщением пользователя должно быть время отправки
  - В разделе чата "Notification" не должно быть диалогового окна с возможностью ввода символов
  - В разделе "Settings" должна быть возможность изменения имени пользователя
  - В разделе "Settings" должна быть возможность выбора языка программирования в качестве вашего оружия для сражения
  - В разделе "Settings" должна быть возможность выбора звукового сопровождения по завершению матча
  - В разделе "Settings" должна быть возможность регулировка громкости звукового сопровождения по завершению матча
  - Кнопки "Lobby/Tournaments/History" должны быть выделены серым цветом при нажатии
  - Кнопки "Lobby/Tournaments/History" должны быть выделены тёмно-серым цветом в момент не задействования
  - Должен быть раздел "Users rating" с отображением рейтинга пользователей
  - Функционал сайта должен отображать пользователей по месту нахождения - Playing/Lobby/online
  - Имя пользователя должно быть не более 16 символов
